title = "viazure"
baseURL = "https://viazure.cc/"

# 设置 <html lang=""> 的值
languageCode = "zh-cn"

# 设置日期格式化的默认语言
defaultContentLanguage = "zh-cn"

# 全局启用 emoji 支持
enableEmoji = true

# 忽略加载额外脚本时的错误
ignoreErrors = ["additional-script-loading-error"]

# 传统方式：主题组件位于 `themes` 目录
theme = "hugo-blog-awesome"

[services]

  # 要启用 Google Analytics 4 (gtag.js)，请在下面提供 G-MEASUREMENT_ID
  # 要禁用 Google Analytics，只需将字段留空或删除以下两行
  [services.googleAnalytics]
    id = "" # G-MEASUREMENT_ID

  # 要启用 Disqus 评论，请提供 Disqus Shortname
  # 要禁用 Disqus 评论，只需将字段留空或删除以下两行
  [services.disqus]
    shortname = ""

# 设置 markup.highlight.noClasses=false 以启用代码高亮
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2 # 目录从 H2 开始
    endLevel = 4   # 目录到 H4 结束
    ordered = false # 生成 <ul> 而不是 <ol>

############################## 中文配置 ################################
[Languages.zh-cn]
  languageName = "Chinese"
  languageCode = "zh-cn"
  contentDir = "content/zh"
  weight = 1

  [Languages.zh-cn.menu]
    [[Languages.zh-cn.menu.main]]
      # pageRef 用于菜单高亮
      # 设置 pageRef 后，设置 url 是可选的；如果找不到页面，它将作为后备选项
      pageRef="/"
      name = "首页"
      url = "/"
      weight = 10
    [[Languages.zh-cn.menu.main]]
      pageRef="posts"
      name = "文章"
      url = "/posts/"
      weight = 20
    [[Languages.zh-cn.menu.main]]
      pageRef="about"
      name = "关于"
      url = "/about/"
      weight = 30

  [Languages.zh-cn.params]
    sitename = "viazure"
    defaultColor = "auto" # 设置颜色模式：dark（深色）, light（浅色）, auto（自动）
    # 设置为 "auto" 时会根据访问者的设备颜色偏好应用配色方案
    # 如果不指定任何内容，忽略此参数或将其留空，默认值设置为 "auto"
    # 你可以查看 layouts/index.html 获取更多信息
    description = "生活是体验，拍照是情绪，写作是思考，折腾是？"
    mainSections = ["posts"]
    toc = false # 设置为 false 可全局禁用目录
    tocOpen = false # 设置为 true 可默认展开目录
    goToTop = true # 设置为 false 可禁用"返回顶部"按钮
     additionalScripts = ["js/custom.js", "js/custom-2.js"]
    # 将尝试加载 "assets/js/custom.js" 和 "assets/js/custom-2.js"
    # 你的自定义脚本将被合并到一个 "custom.js" 文件中
    # 生产环境构建时会进行压缩
    # "custom.js" 文件会在每个页面的 body 标签结束前加载
    dateFormat = "2006-01-02" # 用于在各个页面显示日期的格式。如果未指定，则使用 "2 Jan 2006" 格式
    # 查看 https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference 获取可用的日期格式
    rssFeedDescription = "full" # 可选项：1) summary（摘要）2) full（全文）
    # summary - 在 RSS 源中包含博文的简短摘要。使用 Hugo .Summary 生成
    # full - 在 RSS 源中包含完整博文。使用 Hugo .Content 生成
    # 默认（或未指定）情况下使用 summary

    [Languages.zh-cn.params.author]
      avatar = "avatar.png" # 将文件放在 assets 文件夹中；确保图片具有相同的高度和宽度
      # 注意：如果找不到资源（头像图片），图片不会被渲染。不会显示错误
      intro = "viazure"
      name = "viazure"
      description = "人若无名，可以专心练剑"

    # 允许覆盖 webmanifest 选项
    [Languages.zh-cn.params.webmanifest]
      name = "viazure's blog" # 将使用 "params.sitename" 或 "title" 作为默认值
      short_name = "viazure" # 与 name 相同
      start_url = "/" # 将使用主页 url 作为默认值
      theme_color = "#434648" # 默认为 "#434648"（文本的基色）。还会覆盖 html 的 `<meta name="theme-color" />`
      background_color = "#fff" # 默认根据 "params.defaultColor" 设置，对于 "light" 或 "auto" 将设置为 "#fff"，对于 dark 将设置为 "#131418"（深色模式背景色）
      display = "standalone"

# 允许覆盖 browserconfig.xml 参数（用于 Windows 嵌入式浏览器的配置）
[params.browserconfig]
  TileColor = "#2d89ef" # Windows 10 默认的蓝色磁贴颜色

# 自定义评论系统
[params.comments]

  # Twikoo
  [params.comments.twikoo]
    envId = "https://twikoo-viazure.netlify.app/.netlify/functions/twikoo" # 环境地址，例：https://xxx.netlify.app
    # 下面为可选参数，配置时删除注释符号 `#` 即可。
    # region = "ap-shanghai"  # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；Vercel 环境不填
    # path = ""             # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数
    # lang = "zh-CN"        # 用于手动设定评论区语言，支持的语言列表 https://github.com/twikoojs/twikoo/blob/main/src/client/utils/i18n/index.js

# 自定义统计系统
[params.analytics]

  # GoatCounter
  [params.analytics.goatcounter]
    url = "https://stats.viazure.cc/count" # 为了避免被广告拦截器阻止，建议使用自定义域名
    localSrc = "js/goatcounter.js"  # 本地统计脚本资源路径 (assets/js/goatcounter.js)
    # externalSrc = "https://example.com/goatcounter.js" # 需要使用外部统计脚本资源时取消注释

# Follow 订阅源认证
[params.follow]
  feedId = "96027576665585664"
  userId = "59414119634735104"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/viazure"

[[params.socialIcons]]
  name = "running"
  url = "https://run.viazure.cc"

[[params.socialIcons]]
  name = "Rss"
  url = "/index.xml"
