name: deploy

on:
  push:
    branches:
      - main # 仅 main 分支的 push 触发
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    concurrency: deploy-cf-pages # 并发控制
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Web
        run: hugo

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.BLOG_DEPLOY_TOKEN }}
          publish_dir: ./public
          publish_branch: cf-pages
          force_orphan: true
          keep_files: false
